
# groups:
#   - actions:
#       - a0
#       - a1
#       - a2
#       - a3
#       - a4
#       - a5
#       - a6
#     conditions:
#       - c0
#       - c1
#       - c2
#       - c3


groups:
  - actions:
      - a0
      - a1
      - a2
    conditions:
      - c0
      - c1
      - c2
      