'''
Basic MCTS implementation
Graeme Best
Oregon State University
Jan 2020
'''

from cost import cost
import random
import copy
import numpy as np 
from cfg import Word, Character, CFG, ProductionRule

'''
def rollout(subsequence, action_set, budget):
    # Random rollout policy
    # Pick random actions until budget is exhausted
    num_actions = len(action_set)
    if num_actions <= 0:
        raise ValueError('rollout: num_actions is ' + str(num_actions))
    sequence = copy.deepcopy(subsequence)
    while cost(sequence) < budget:
        r = random.randint(0,num_actions-1)
        sequence.append(action_set[r])

    return sequence

'''

def rollout(partial_word, cfg, budget):

    current_word = partial_word
    
    # If partial_word is not terminal, then apply rules randomly until it generates a word that is and return
    num_rules_applied = 0
    while num_rules_applied < budget:

        # If current word is not terminal, generate random new word that may or may not be terminal
        new_word = applyRandomProductionRule(current_word,cfg)

        # Check if new word is terminal
        if not new_word: #partial word is terminal
            return current_word

        # Count rule applied
        num_rules_applied += 1

        # Reset current word, so you can check if new_word is terminal, and if not, apply a new random rule to it
        current_word = new_word


    print('rollout over budget: ' + current_word.toString())
    # Return empty word
    return Word([])


def applyRandomProductionRule(partial_word,cfg):
    '''
    If it returns none, then the partial word is terminal
    Else: we return a random viable new word generated by one of our production rules
    '''

    random_order = np.random.permutation(len(cfg.grammar))

    for i in random_order:
        output_word_list = cfg.grammar[i].applyProductionRule(partial_word)

        if len(output_word_list) != 0:
            return output_word_list[random.randint(0,len(output_word_list)-1)]

    return None



